networks:
  dash_network:
    driver: bridge

services:
  dash_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'python main.py'
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - dash_network
    ports:
      - '8050:8050'
      - '8052:8052'
    restart: always
    volumes:
      - '.:/app'